# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: mixi 1.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "mixi"
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Svetlana Tarasova", "axl"]
  s.date = "2020-09-30"
  s.email = "axl1232@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "init.rb",
    "install",
    "lib/mixi.rb",
    "lib/mixi/config.rb",
    "lib/mixi/engine.rb",
    "lib/mixi/middleware.rb",
    "lib/mixi/oauth.rb",
    "lib/mixi/payment_validator.rb",
    "lib/mixi/rails/controller.rb",
    "lib/mixi/rails/controller/redirects.rb",
    "lib/mixi/request_validator.rb",
    "lib/mixi/user.rb",
    "mixi.gemspec"
  ]
  s.homepage = "http://github.com/axl1232/mixi"
  s.rubygems_version = "2.5.1"
  s.summary = "Mixi integration for Rack & Rails application"
end

